### PR TITLE
Byte array fix

### PR DESCRIPTION
**Pull request by oetyng**
Replaced all instances of `List<byte>` with `byte[]`.  

Simple fix for https://github.com/maidsafe/safe_app_csharp/issues/39#issue-382903507 until https://github.com/maidsafe/safe_bindgen/issues/42#issue-429699029 has been solved.

### CODE REVIEW

**Comment by ravinderjangra** [comment]
For now are going to remove these API so I think these changes are not required and can be directly implemented in new APIs

**Comment by oetyng** [comment]
> For now are going to remove these API so I think these changes are not required and can be directly implemented in new APIs

It would serve as a good starting point for the new APIs. The old ones are not removed yet, and not all of what's included here will be removed. And the work is already done :)
So,it could just as well be merged, no?

**Comment by ravinderjangra** [comment]
Even if we merge this, we still can't use these API the `IntPtr` in these API should point the `safe_app` in SCL FFI while in the new APIs the `IntPtr` points to the `Safe` object that belongs to `safe-cli` so basically we wouldn't be able to call these APIs for now unless some changes are made to the `safe-cli` structure to call HL and LL APIs interchangeably from the same Session/SafeApp object/IntPtr.

**Comment by oetyng** [comment]
But that's another problem, another issue to raise and work on, not related to this PR. In the meantime this thing is fixed.

 If the old API is removed, then part of changes in this PR is removed, nothing is affected by it. It's not harder to keep or not keep the API due to this improvement. If it's not removed, then this is still here. But nothing in future work is affected negatively by merging this. We're just removing this wrong code, and putting in correct code.

So, as you said, not required, but that's why I did it on my free time, to just fix up such small things that are not the absolute most urgent.

**Comment by ravinderjangra** [comment]
I am happy to merge this but I think you will have to rebase this PR Because first 3/4 changes are already merged.

What do you think about raising the same or for master brach too? At least that way we can confirm that the changes are working fine with older bindings and  test just to be sure that this wouldn't create any problem in future? What's do you think about this?

**Comment by oetyng** [comment]
Ah the previous PR was squashed, yep I'll do it no prob.
Sure, I'll raise it for Master as well.

**Pull request merged**
